"""Initial migration

Revision ID: 5b006a57185f
Revises:
Create Date: 2024-07-02 08:51:18.784445

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5b006a57185f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
