"""adding initial tables

Revision ID: d8004db4651f
Revises: 5b006a57185f
Create Date: 2024-07-02 08:57:13.651636

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d8004db4651f"
down_revision: Union[str, None] = "5b006a57185f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
