# Base Stage
FROM node:18-alpine AS base-stage

WORKDIR /code

COPY package.json package-lock.json ./

RUN npm install

COPY ./ /code

# Development Stage
FROM base-stage AS dev-stage

# Copy the appropriate environment file for development
# COPY .env.development .env

# Expose the port that the development server runs on
EXPOSE 5173

# Start the React app in development mode
CMD ["npm", "start"]
